@echo off
echo Starting Focus Voucher System...
echo.
echo Checking .NET Runtime...
dotnet --version
echo.
echo Running application...
FocusVoucherSystem.exe
echo.
echo Application ended. Press any key to close...
pause